// NEW COLORS. EVENTUALLY DELETE ^^^
export const AZURE = '#3A62A3'
export const NEPTUNE = '#71BAAF'
export const STEEL_BLUE = '#4A73B9'
export const VALENCIA = '#D04A42'
export const SUPERNOVA = '#FFC907'
export const BRANDY_PUNCH = '#F79226'
export const DESERT_STORM = '#F6F6F5'
export const DUSTY_GRAY = '#999999'
export const BLACK = '#000000'
export const WHITE = '#FFFFFF'
